export type UPVCBadgeKey =
  | "security"
  | "thermal"
  | "acoustic"
  | "weather"
  | "energy"
  | "design";

export type UPVCProduct = {
  id: string;
  title: string;
  desc: string;
  img: string;
  tag: string;
  specs: [string, string, string, string];
  badgeKeys: UPVCBadgeKey[];
  category: "door";
};

export const upvcDoorProducts: UPVCProduct[] = [
  {
    id: "sliding-doors",
    title: "Sliding Doors",
    desc: "Panoramic sliding doors with minimal sightlines and smooth heavy-duty rollers for modern facades.",
    img: "/images/upvc/sliding-door.png",
    tag: "Premium",
    specs: ["200kg rollers", "Low threshold", "Anti-derail track", "Argon-ready glazing"],
    badgeKeys: ["security", "thermal", "energy"],
    category: "door",
  },
  {
    id: "french-doors",
    title: "French Doors",
    desc: "Classic double-panel doors that create an elegant transition to terraces, balconies, and gardens.",
    img: "/images/upvc/french-door.png",
    tag: "Luxury",
    specs: ["Flush bolt", "3-point lock", "Decorative glazing", "Low-E glass"],
    badgeKeys: ["design", "security", "acoustic"],
    category: "door",
  },
  {
    id: "pivot-doors",
    title: "Pivot Doors",
    desc: "Statement-making oversized pivot systems engineered for villa entrances and premium residential facades.",
    img: "/images/upvc/villa.png",
    tag: "Signature",
    specs: ["Offset pivot hinge", "Large panel format", "Slim frame lines", "Luxury finishes"],
    badgeKeys: ["design", "security", "thermal"],
    category: "door",
  },
  {
    id: "bi-fold-doors",
    title: "Bi-Fold Doors",
    desc: "Flexible folding door systems that open up entire walls for indoor-outdoor luxury living.",
    img: "/images/upvc/sliding-door.png",
    tag: "Architect",
    specs: ["Multi-panel folding", "Smooth carriage set", "Wide opening span", "Weather-sealed joints"],
    badgeKeys: ["weather", "design", "energy"],
    category: "door",
  },
  {
    id: "patio-doors",
    title: "Patio Doors",
    desc: "Light, refined patio sliders designed to bring in more daylight while preserving insulation and comfort.",
    img: "/images/upvc/hero.png",
    tag: "Best Seller",
    specs: ["Slim track profile", "Easy glide wheels", "Wide glass panels", "Brush seal barrier"],
    badgeKeys: ["thermal", "energy", "weather"],
    category: "door",
  },
  {
    id: "lift-slide-doors",
    title: "Lift & Slide Doors",
    desc: "Premium large-panel doors that lift off the seal for ultra-smooth movement and superior sealing performance.",
    img: "/images/upvc/sliding-door.png",
    tag: "Elite",
    specs: ["Lift-slide hardware", "Large format sash", "Enhanced air seal", "Luxury glazing options"],
    badgeKeys: ["weather", "energy", "design"],
    category: "door",
  },
  {
    id: "pocket-doors",
    title: "Pocket Sliding Doors",
    desc: "Modern disappearing sliders that recess neatly for cleaner openings and uninterrupted views.",
    img: "/images/upvc/sliding-door.png",
    tag: "Modern",
    specs: ["Pocket-ready layout", "Hidden stack option", "Soft-close motion", "Panoramic opening"],
    badgeKeys: ["design", "energy", "weather"],
    category: "door",
  },
  {
    id: "telescopic-doors",
    title: "Telescopic Doors",
    desc: "Multi-track telescopic door systems that stack elegantly and maximize the clear opening width.",
    img: "/images/upvc/sliding-door.png",
    tag: "Advanced",
    specs: ["Multi-sash slide", "Space optimized", "Smooth synchronized motion", "Heavy-duty track"],
    badgeKeys: ["design", "security", "weather"],
    category: "door",
  },
  {
    id: "corner-doors",
    title: "Corner Sliding Doors",
    desc: "Architectural corner-opening door systems for villas and premium lounges with dramatic full-corner views.",
    img: "/images/upvc/villa.png",
    tag: "Luxury",
    specs: ["Corner opening", "Minimal mullion look", "Premium carriage set", "Wide glazed panels"],
    badgeKeys: ["design", "energy", "thermal"],
    category: "door",
  },
  {
    id: "balcony-doors",
    title: "Balcony Doors",
    desc: "Compact and elegant balcony access doors tuned for insulation, security, and easy daily use.",
    img: "/images/upvc/french-door.png",
    tag: "Urban",
    specs: ["Compact threshold", "Balcony-ready lock", "Daylight glazing", "Easy maintenance finish"],
    badgeKeys: ["security", "thermal", "weather"],
    category: "door",
  },
  {
    id: "terrace-doors",
    title: "Terrace Doors",
    desc: "Weather-protected terrace systems built for outdoor exposure with a cleaner premium exterior finish.",
    img: "/images/upvc/french-door.png",
    tag: "Outdoor",
    specs: ["High weather seal", "Drainage channel", "UV-stable profile", "Corrosion-safe hardware"],
    badgeKeys: ["weather", "thermal", "security"],
    category: "door",
  },
  {
    id: "villa-entrance-doors",
    title: "Villa Entrance Doors",
    desc: "Luxury main entrance doors with stronger section depths, richer finishes, and bold architectural presence.",
    img: "/images/upvc/villa.png",
    tag: "Grand",
    specs: ["Main-door build", "Decorative panel options", "High-security locking", "Premium matte finish"],
    badgeKeys: ["design", "security", "thermal"],
    category: "door",
  },
  {
    id: "double-leaf-doors",
    title: "Double Leaf Doors",
    desc: "Balanced dual-leaf door sets for formal entrances, drawing rooms, and premium transition spaces.",
    img: "/images/upvc/french-door.png",
    tag: "Classic",
    specs: ["Dual opening leaves", "Flush bolt system", "Elegant symmetry", "Decorative glazing"],
    badgeKeys: ["design", "security", "acoustic"],
    category: "door",
  },
  {
    id: "arched-french-doors",
    title: "Arched French Doors",
    desc: "French-style UPVC doors with arched proportions for a softer classical facade language.",
    img: "/images/upvc/french-door.png",
    tag: "Heritage",
    specs: ["Arched profile option", "Custom mullions", "Premium hinge set", "Made-to-measure sizing"],
    badgeKeys: ["design", "thermal", "weather"],
    category: "door",
  },
  {
    id: "designer-panel-doors",
    title: "Designer Panel Doors",
    desc: "Decorative panel doors combining modern UPVC durability with elevated front-door styling.",
    img: "/images/upvc/hero.png",
    tag: "Designer",
    specs: ["Decor panel insert", "Textured finish option", "Front-entry hardware", "Low maintenance skin"],
    badgeKeys: ["design", "security", "energy"],
    category: "door",
  },
  {
    id: "glass-doors",
    title: "Glass Doors",
    desc: "Slim-framed glass-heavy door systems for brighter interiors and cleaner premium visual flow.",
    img: "/images/upvc/sliding-door.png",
    tag: "Minimal",
    specs: ["High-glass ratio", "Slim perimeter frame", "Clear glazing option", "Modern handle sets"],
    badgeKeys: ["design", "energy", "acoustic"],
    category: "door",
  },
  {
    id: "frosted-glass-doors",
    title: "Frosted Glass Doors",
    desc: "Privacy-focused glazed doors that preserve daylight while softening visibility for interiors and utilities.",
    img: "/images/upvc/casement.png",
    tag: "Private",
    specs: ["Frosted glazing", "Privacy finish", "Light transmission", "Easy-clean surface"],
    badgeKeys: ["design", "thermal", "weather"],
    category: "door",
  },
  {
    id: "courtyard-doors",
    title: "Courtyard Doors",
    desc: "Openable courtyard-facing systems created for brighter inner spaces and luxury air-light movement.",
    img: "/images/upvc/villa.png",
    tag: "Lifestyle",
    specs: ["Wide opening mode", "Garden-facing design", "Strong weather strip", "Indoor-outdoor flow"],
    badgeKeys: ["energy", "weather", "design"],
    category: "door",
  },
  {
    id: "utility-doors",
    title: "Utility Doors",
    desc: "Practical service and back-entry doors with weather-ready detailing and long-wear hardware performance.",
    img: "/images/upvc/casement.png",
    tag: "Functional",
    specs: ["Back-entry design", "Moisture resistant", "Easy clean finish", "Durable hardware"],
    badgeKeys: ["weather", "security", "energy"],
    category: "door",
  },
  {
    id: "louvered-doors",
    title: "Louvered Doors",
    desc: "Ventilation-friendly UPVC louvered doors suitable for service areas, wash zones, and utility spaces.",
    img: "/images/upvc/casement.png",
    tag: "Ventilated",
    specs: ["Airflow louvers", "Moisture-safe build", "Low upkeep profile", "Custom panel split"],
    badgeKeys: ["weather", "energy", "design"],
    category: "door",
  },
  {
    id: "security-doors",
    title: "Security Doors",
    desc: "Reinforced UPVC security doors combining durable framing with stronger locking and safe daily operation.",
    img: "/images/upvc/soundproof.png",
    tag: "Safe",
    specs: ["Reinforced section", "Multi-point lock", "Secure hinge side", "Impact-ready hardware"],
    badgeKeys: ["security", "weather", "thermal"],
    category: "door",
  },
  {
    id: "mesh-doors",
    title: "Mesh Doors",
    desc: "Secondary insect and ventilation doors that pair with main entrance systems for comfort and airflow.",
    img: "/images/upvc/casement.png",
    tag: "Comfort",
    specs: ["Mesh integration", "Fresh-air access", "Bug-safe screen", "Lightweight operation"],
    badgeKeys: ["weather", "energy", "design"],
    category: "door",
  },
  {
    id: "soundproof-doors",
    title: "Soundproof Doors",
    desc: "Acoustic-grade door systems built for quieter interiors in urban homes, studios, and premium bedrooms.",
    img: "/images/upvc/soundproof.png",
    tag: "Acoustic",
    specs: ["Acoustic seal set", "Laminated glazing", "Noise-control core", "Premium closure system"],
    badgeKeys: ["acoustic", "security", "thermal"],
    category: "door",
  },
  {
    id: "heritage-hinged-doors",
    title: "Heritage Hinged Doors",
    desc: "Traditional-style hinged doors with timeless proportions and modern UPVC performance at the core.",
    img: "/images/upvc/french-door.png",
    tag: "Timeless",
    specs: ["Hinged opening", "Classic detailing", "Modern insulation", "Color-match finish"],
    badgeKeys: ["design", "thermal", "security"],
    category: "door",
  },
];

export const featuredUPVCDoorProducts = upvcDoorProducts.slice(0, 6);

export const upvcDoorCount = upvcDoorProducts.length;
